version: '3.9'

services:
  frontend:
    build: 
      context: ./frontend
    ports:
      - "4200:80"
    networks:
      - app-network

  gateway:
    build: 
      context: ./gateway
    ports:
      - "8080:8080"
    depends_on:
      - auth-service
    networks:
      - app-network

  auth-service:
    build: 
      context: ./auth-service
    ports:
      - "8081:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge